export const ARCHITECTURE_DATA = {
  canvas: {
    width: 1760,
    height: 1080,
    centerX: 720,
    centerY: 560,
  },
  layout: {
    preserveManualPositions: true,
  },
  zones: [
    { id: 'sdg-campus', title: 'SDG-Campus' },
    { id: 'on-prem', title: 'On-Prem' },
    { id: 'de-region', title: 'DE Region' },
    { id: 'eu-cloud', title: 'EU Cloud' },
    { id: 'us-global', title: 'US/Global (Externe Services)' },
  ],
  rings: [
    { id: 'us-global', title: 'US/Global (Externe Services)', rx: 850, ry: 850, labelOffsetY: 330, className: 'zone-ring--us-global' },
    { id: 'eu-cloud', title: 'EU Cloud', rx: 815, ry: 520, labelOffsetY: 42, className: 'zone-ring--eu-cloud' },
    { id: 'de-region', title: 'DE Region', rx: 690, ry: 500, labelOffsetY: 42, className: 'zone-ring--de-region' },
    { id: 'on-prem', title: 'On-Prem', rx: 670, ry: 370, labelOffsetY: 42, className: 'zone-ring--on-prem' },
    { id: 'sdg-campus', title: 'SDG-Campus', rx: 254, ry: 254, labelOffsetY: 42, className: 'zone-ring--sdg-campus' },
  ],
  groups: [
    {
      id: 'sdg-campus-cluster',
      label: 'SDG CAMPUS Umgebung',
      zone: 'sdg-campus',
      x: 563,
      y: 417,
      width: 304,
      height: 286,
      nodeIds: ['moodle-lms'],
      description: 'Moodle mit eingebettetem AI Interface (LTI), Course UI und Author UI.',
    },
    {
      id: 'core-cluster',
      label: 'Content & Information Core',
      zone: 'on-prem',
      x: 130,
      y: 385,
      width: 290,
      height: 350,
      nodeIds: ['policy-engine', 'skis', 'content-core', 'lrs'],
      description: 'Content-, Wissens- und Governance-Bausteine inklusive LRS in der lokalen Zone.',
    },
    {
      id: 'capabilities-cluster',
      label: 'AI Workflow Engine',
      zone: 'on-prem',
      x: 1020,
      y: 385,
      width: 300,
      height: 350,
      nodeIds: ['authoring-studio', 'insights-engine', 'pathway-engine', 'learning-companion'],
      description: 'KI-Funktionen fuer Authoring, Insights, Lernpfade und Tutor-Unterstuetzung.',
    },
  ],
  serviceNodeIds: [
    'moodle-lms',
    'localization-pipeline',
    'language-mediation',
    'sap-openai-germany',
    'model-providers',
    'external-services',
  ],
  embeddedNodes: [
    {
      id: 'embedded-ai-interface',
      parentNodeId: 'moodle-lms',
      label: 'AI Interface (LTI)',
      zone: 'sdg-campus',
      dataClass: 'system',
      shortDescription: 'LTI-basierte Integrationsschicht fuer KI-Funktionen im Moodle-Kontext.',
      longDescription: [
        'Verbindet Moodle sicher mit den CampusConnect-Funktionen.',
        'Uebernimmt Launch, Kontext und Rechte fuer integrierte Lern- und Autorenoberflaechen.',
        'Schafft die technische Basis fuer Course UI und Author UI.',
      ],
      purpose: [
        'Moodle-Kontext sicher uebergeben.',
        'AI-Features in die bestehende Plattform einbetten.',
        'Konsistente Integrationslogik bereitstellen.',
      ],
      inputs: ['Moodle Kurs-/Sessionkontext', 'LTI Launch-Informationen'],
      outputs: ['Course UI Kontexte', 'Author UI Kontexte'],
      securityNotes: [
        'Keine eigenstaendige PII-Speicherung.',
        'Kommunikation bleibt in der SDG-Campus Zone.',
      ],
    },
    {
      id: 'embedded-course-ui',
      parentNodeId: 'moodle-lms',
      label: 'Course UI',
      zone: 'sdg-campus',
      dataClass: 'mixed',
      shortDescription: 'Lernoberflaeche fuer Studierende innerhalb des Moodle-Kurses.',
      longDescription: [
        'Zeigt Inhalte, Aufgaben und KI-gestuetzte Unterstuetzung im Kurskontext.',
        'Erfasst Lerninteraktionen im Rahmen der Plattformnutzung.',
        'Baut auf dem AI Interface auf und bleibt in die Moodle-Nutzung eingebettet.',
      ],
      purpose: [
        'Lernaktivitaeten im Kurs ermoeglichen.',
        'Tutor- und Pfadfunktionen nutzerfreundlich bereitstellen.',
        'Direkte Studierenden-Interaktion im Kurskontext.',
      ],
      inputs: ['Kurskontext aus AI Interface', 'Kursinhalte aus Moodle'],
      outputs: ['Lerninteraktionen', 'Anfragen an weitere CampusConnect-Bausteine'],
      securityNotes: [
        'PII-nahe Nutzungsdaten entstehen lokal im Kurskontext.',
        'Externe Weitergabe nur ueber nachgelagerte Policy-Pfade.',
      ],
    },
    {
      id: 'embedded-author-ui',
      parentNodeId: 'moodle-lms',
      label: 'Author UI',
      zone: 'sdg-campus',
      dataClass: 'non-pii',
      shortDescription: 'Autorenoberflaeche fuer Lehrende zur KI-unterstuetzten Kurserstellung.',
      longDescription: [
        'Erlaubt Lehrenden, Inhalte zu erstellen und zu kuratieren.',
        'Nutzen und Ausgabe erfolgen im Moodle- und LTI-Kontext.',
        'Dient als Bruecke zu den spaeteren Authoring- und Core-Komponenten.',
      ],
      purpose: [
        'Lehrendenworkflow in Moodle integrieren.',
        'Kurserstellung vereinfachen.',
        'Grundlage fuer AI-gestuetztes Authoring schaffen.',
      ],
      inputs: ['Lehrenden-Kontext aus AI Interface', 'Kurs-/Strukturdaten aus Moodle'],
      outputs: ['Authoring-Anfragen', 'Inhaltsentwuerfe'],
      securityNotes: [
        'Fokus auf nicht-personenbezogene Inhaltsarbeit.',
        'Rechte- und Rollenkontext bleiben in der Plattform.',
      ],
    },
  ],
  nodes: [
    {
      id: 'moodle-lms',
      label: 'Moodle LMS',
      zone: 'sdg-campus',
      dataClass: 'system',
      x: 581,
      y: 440,
      width: 268,
      height: 240,
      visualType: 'platform',
      renderKind: 'moodle-shell',
      logoSrc: 'assets/moodle-logo.svg',
      shortDescription: 'Bestehendes LMS, in das AI Interface (LTI), Course UI und Author UI eingebettet werden.',
      longDescription: [
        'Stellt Kurse, Rollen und Kurslogik fuer Lehrende und Lernende bereit.',
        'Das AI Interface (LTI) wird innerhalb von Moodle entwickelt und eingebettet.',
        'Course UI und Author UI werden als integrierte Oberflaechen in Moodle bereitgestellt.',
      ],
      purpose: [
        'Bestehende SDG-Campus Plattform nutzen.',
        'Einbettung neuer KI-UI-Bausteine ohne Systembruch.',
        'Plattformkontext fuer nachgelagerte Bausteine bereitstellen.',
      ],
      inputs: ['Kursinhalte aus dem Content Core', 'Kurskonfigurationen, Rollen und Enrollment'],
      outputs: ['Course UI Interaktionen (PII lokal)', 'Author UI Authoring-Anfragen', 'Moodle/LTI-Kontext fuer CampusConnect'],
      securityNotes: ['Campus-intern betrieben.', 'PII bleibt in lokalen Systemgrenzen.'],
    },
    {
      id: 'policy-engine',
      label: 'AI Workflow & Policy Engine',
      zone: 'on-prem',
      dataClass: 'system',
      x: 175,
      y: 423,
      width: 210,
      height: 60,
      icon: '🛡️',
      shortDescription: 'Policy-gesteuertes Routing, Logging und Freigabe-Gate für alle KI-Workflows.',
      longDescription: [
        'Prüft jeden Request gegen Datenklassen- und Sicherheitsregeln.',
        'Steuert, ob ein Request lokal bleibt oder non-PII extern verarbeitet wird.',
        'Erzeugt durchgängige Audit-Logs für Governance und Nachweisbarkeit.',
      ],
      purpose: [
        'Policy-Enforcement zentralisieren.',
        'Datenabflüsse kontrollieren.',
        'Logging und Compliance absichern.',
      ],
      inputs: ['Routing-Anfragen aus Companion und Pathway Engine'],
      outputs: ['Freigegebene Calls zu externen Services (non-PII)', 'Policy-/Audit-Events'],
      securityNotes: ['PII bleibt lokal; externe Calls werden auf non-PII reduziert.', 'Alle externen Requests sind protokolliert und nachvollziehbar.'],
      faq: [
        {
          q: 'Geht PII an externe Modellanbieter?',
          a: 'Nein. Die Policy Engine blockiert oder transformiert Requests, wenn sie PII enthalten.',
        },
      ],
      apMapping: 'AP 1.2 – Governance für Tutor- und Pathway-Interaktionen',
    },
    {
      id: 'skis',
      label: 'SKIS',
      subtitle: 'Standard Knowledge & Information System',
      zone: 'on-prem',
      dataClass: 'non-pii',
      x: 175,
      y: 503,
      width: 210,
      height: 60,
      shortDescription: 'Standardisierte Wissensbasis für strukturierte Inhalte und Referenzen.',
      longDescription: [
        'Hält normierte Wissensobjekte für Wiederverwendung bereit.',
        'Ermöglicht konsistente Referenzdaten in Authoring und Tutor-Funktionen.',
        'Unterstützt domänenspezifische Wissensmodelle für Lernkontexte.',
      ],
      purpose: [
        'Wissensbasis vereinheitlichen.',
        'Inhaltskonsistenz sichern.',
        'Wiederverwendung beschleunigen.',
      ],
      inputs: ['Kuratiertes Fachwissen', 'Metadaten und Klassifizierungen'],
      outputs: ['Standardisierte Wissensobjekte für Content Core und Tutor'],
      securityNotes: ['Typisch non-PII.', 'Versionierung und Herkunftsnachweis im On-Prem-Kern.'],
    },
    {
      id: 'audit-hitl',
      label: 'Audit / Freigabe / Human-in-the-Loop',
      displayLabel: 'Audit / Freigabe / HITL',
      zone: 'on-prem',
      allowOutsideZone: true,
      dataClass: 'system',
      x: 1360,
      y: 176,
      width: 210,
      height: 60,
      shortDescription: 'Menschliche Qualitätskontrolle für kritische oder freigabepflichtige Inhalte.',
      longDescription: [
        'Bietet Freigabeschritte vor Veröffentlichung sensibler Inhalte.',
        'Erlaubt Eskalation bei Unsicherheit oder Policy-Verletzungen.',
        'Dokumentiert Entscheidungen für Audit und Qualitätssicherung.',
      ],
      purpose: [
        'Qualität sichern.',
        'Risiken vor Veröffentlichung minimieren.',
        'Governance-Anforderungen erfüllen.',
      ],
      inputs: ['Freigabepflichtige Inhalte und Änderungsanträge'],
      outputs: ['Freigabe-/Ablehnungsentscheidungen', 'Audit-Nachweise'],
      securityNotes: ['Human-in-the-Loop als zusätzliche Sicherheitsbarriere.', 'Nachvollziehbare Entscheidungsdokumentation.'],
      faq: [
        {
          q: 'Wie wird Qualität gesichert?',
          a: 'Über Audit/HITL mit dokumentierten Freigaben vor produktiver Auslieferung.',
        },
      ],
    },
    {
      id: 'content-core',
      label: 'Content & Competency Core',
      subtitle: 'SSOT, RAG-ready',
      zone: 'on-prem',
      dataClass: 'non-pii',
      x: 175,
      y: 583,
      width: 210,
      height: 60,
      shortDescription: 'Single Source of Truth für Inhalte, Kompetenzen und strukturierte Lernbausteine.',
      longDescription: [
        'Verwaltet versionierte Lerninhalte und Kompetenzmodelle zentral.',
        'Beliefert Authoring, Pathway und Companion konsistent mit denselben Artefakten.',
        'Ist vorbereitet für RAG- und Retrieval-basierte Tutor-Szenarien.',
      ],
      purpose: [
        'Inhalte zentral verwalten.',
        'Kompetenzmodelle konsistent halten.',
        'Downstream-Services synchron versorgen.',
      ],
      inputs: ['Authoring-Outputs', 'Kompetenzmodelle', 'Freigegebene Übersetzungsartefakte'],
      outputs: ['Tutor Content', 'Pathway-Daten', 'Kurs-Publishing und Localization-Feeds'],
      securityNotes: ['Primär non-PII.', 'Freigaben über Audit/HITL möglich.'],
      apMapping: 'AP 1.2 – Grundlage für Tutor, Pathways und Lokalisierung',
    },
    {
      id: 'lrs',
      label: 'Learning Record Store (LRS)',
      displayLabel: 'Learning Record Store (LRS)',
      subtitle: 'PII Zone',
      zone: 'on-prem',
      dataClass: 'pii',
      x: 175,
      y: 663,
      width: 210,
      height: 60,
      shortDescription: 'On-Prem-Speicher für Lernaktivitäten mit Personenbezug.',
      longDescription: [
        'Speichert Ereignisse, Fortschritt und Interaktionshistorie personenbezogen.',
        'Ermöglicht Lernanalysen ohne PII-Export in externe Systeme.',
        'Bildet die Datenbasis für Insights und personalisierte Lernpfade.',
      ],
      purpose: [
        'Lerndaten lokal persistieren.',
        'PII-Compliance absichern.',
        'Insights lokal ermöglichen.',
      ],
      inputs: ['Learner-Aktivitäten aus Course UI'],
      outputs: ['PII-Insights für Learning Insights Engine'],
      securityNotes: ['Explizite PII-Zone in DE/on-prem.', 'Direkter externer Zugriff ausgeschlossen.'],
      faq: [
        {
          q: 'Wo liegen Lerndaten?',
          a: 'Im LRS in der PII-Zone auf On-Prem-Infrastruktur.',
        },
      ],
    },
    {
      id: 'authoring-studio',
      label: 'Authoring Studio',
      subtitle: 'AI-assisted',
      zone: 'on-prem',
      dataClass: 'non-pii',
      x: 1065,
      y: 423,
      width: 210,
      height: 60,
      shortDescription: 'KI-unterstützte Erstellung und Überarbeitung von Lerninhalten.',
      longDescription: [
        'Unterstützt Lehrende bei Strukturierung, Formulierung und didaktischer Aufbereitung.',
        'Nutzt zentrale Inhalte und Kompetenzen als Kontext.',
        'Publiziert validierte Inhalte zurück in den Content Core.',
      ],
      purpose: [
        'Autor:innen produktiver machen.',
        'Didaktische Konsistenz stärken.',
        'Freigabefähige Inhalte erzeugen.',
      ],
      inputs: ['Bestehende Lerninhalte', 'Kompetenzziele', 'SKIS-Wissensobjekte'],
      outputs: ['Content Publishing in den Content Core'],
      securityNotes: ['Standardmäßig non-PII.', 'Risikobehaftete Inhalte können in Audit/HITL gehen.'],
      apMapping: 'AP 1.2 – AI-gestütztes Authoring',
    },
    {
      id: 'insights-engine',
      label: 'Learning Insights Engine',
      zone: 'on-prem',
      dataClass: 'pii',
      x: 1065,
      y: 503,
      width: 210,
      height: 60,
      shortDescription: 'Berechnet Lernfortschritt und Signale für adaptive Entscheidungen.',
      longDescription: [
        'Verarbeitet PII-nahe Lernverläufe aus dem LRS lokal.',
        'Erzeugt Insight-Signale für Personalisierung und Frühwarnindikatoren.',
        'Versorgt die Pathway Engine mit aktuellen Lernmustern.',
      ],
      purpose: [
        'Lernmuster erkennen.',
        'Adaptionssignale bereitstellen.',
        'Datengestützte Pfadentscheidungen ermöglichen.',
      ],
      inputs: ['PII-Events aus dem LRS'],
      outputs: ['Insights Sync an Adaptive Pathway Engine'],
      securityNotes: ['PII-Verarbeitung lokal im On-Prem-Ring.', 'Keine direkten externen Exporte.'],
      apMapping: 'AP 1.2 – Learning Insights als Input für adaptive Pfade',
    },
    {
      id: 'pathway-engine',
      label: 'Adaptive Pathway Engine',
      zone: 'on-prem',
      dataClass: 'mixed',
      x: 1065,
      y: 583,
      width: 210,
      height: 60,
      shortDescription: 'Leitet personalisierte Lernpfade aus Insights und Kompetenzmodellen ab.',
      longDescription: [
        'Kombiniert Kompetenzen (non-PII) mit Lernsignalsichten (PII) zu Empfehlungen.',
        'Erzeugt adaptive Sequenzen für die nächste Lernphase.',
        'Routet externe Assistenz-Anteile ausschließlich policy-konform.',
      ],
      purpose: [
        'Lernpfade personalisieren.',
        'Kompetenzlücken adressieren.',
        'Tutor-Interaktionen kontextualisieren.',
      ],
      inputs: ['Insights Sync', 'Pathways/Kompetenzdaten aus Content Core'],
      outputs: ['Pathway Routing zur Policy Engine', 'Empfehlungen für Course UI'],
      securityNotes: ['Mixed-Datenklasse durch Kombination aus PII- und non-PII-Signalen.', 'Externe Weitergabe nur über Policy Engine.'],
      apMapping: 'AP 1.2 – Adaptive Lernpfade',
    },
    {
      id: 'learning-companion',
      label: 'Learning Companion',
      subtitle: 'In-Course Assistant',
      zone: 'on-prem',
      dataClass: 'mixed',
      x: 1065,
      y: 663,
      width: 210,
      height: 60,
      shortDescription: 'Tutor-Assistent im Kurs mit kontextbasierten Hilfen und Erklärungen.',
      longDescription: [
        'Nutzt Content Core als primäre Wissensquelle für Antworten.',
        'Unterstützt Lernende direkt im Lernfluss mit erklärenden Hinweisen.',
        'Delegiert externe Services nur nach Policy-Entscheidung.',
      ],
      purpose: [
        'Tutor-Funktion im Kurs anbieten.',
        'Kontextbezogene Hilfe liefern.',
        'Nutzung externer Modelle kontrolliert ermöglichen.',
      ],
      inputs: ['Tutor Content aus Content Core', 'Lernkontext aus Course UI'],
      outputs: ['Routing-Anfragen an Policy Engine', 'Optional Translation-Requests'],
      securityNotes: ['Mixed-Datenklasse, weil Lernkontext verarbeitet wird.', 'Keine direkten externen Calls ohne Policy-Prüfung.'],
      apMapping: 'AP 1.2 – Companion/Tutor im Lernkontext',
    },
    {
      id: 'localization-pipeline',
      label: 'Content Localization Pipeline',
      displayLabel: 'Localization Pipeline',
      subtitle: 'Batch (optional)',
      zone: 'eu-cloud',
      dataClass: 'non-pii',
      x: 1104,
      y: 428,
      optional: true,
      shortDescription: 'Optionale Batch-Lokalisierung für Kursinhalte in EU-Cloud-Umgebung.',
      longDescription: [
        'Übersetzt freigegebene non-PII-Inhalte für mehrsprachige Ausspielung.',
        'Arbeitet asynchron und versionsbasiert auf Content-Artefakten.',
        'Gibt lokalisierte Ergebnisse zur kuratierten Übernahme zurück.',
      ],
      purpose: [
        'Mehrsprachigkeit vorbereiten.',
        'Batch-Übersetzungen automatisieren.',
        'Lokalisierte Inhalte versionieren.',
      ],
      inputs: ['Localization-Requests aus Content Core (non-PII)'],
      outputs: ['Lokalisierte Inhaltsvarianten'],
      securityNotes: ['Nur non-PII erlaubt.', 'Optionale Komponente, kann vollständig deaktiviert werden.'],
      apMapping: 'AP 1.2 – Übersetzung/Lokalisierung (Batch)',
    },
    {
      id: 'language-mediation',
      label: 'Realtime Language Mediation',
      displayLabel: 'Language Mediation',
      subtitle: 'Runtime (optional)',
      zone: 'de-region',
      dataClass: 'non-pii',
      x: 610,
      y: 950,
      optional: true,
      shortDescription: 'Optionale Laufzeit-Übersetzung für Tutor-Interaktionen.',
      longDescription: [
        'Mediiert Spracheingaben in Echtzeit für mehrsprachige Lernsituationen.',
        'Kann bei Bedarf je Kurs oder Nutzergruppe aktiviert werden.',
        'Unterliegt denselben non-PII und Logging-Regeln wie andere externe Dienste.',
      ],
      purpose: [
        'Mehrsprachige Tutor-Läufe ermöglichen.',
        'Runtime-Übersetzungen bereitstellen.',
        'Didaktische Barrieren senken.',
      ],
      inputs: ['Translation-Requests aus Learning Companion (non-PII)'],
      outputs: ['Sprachvermittelte Antworten an Companion'],
      securityNotes: ['Nur non-PII.', 'Optional und abschaltbar.'],
      apMapping: 'AP 1.2 – Übersetzung/Lokalisierung (Runtime)',
    },
    {
      id: 'sap-openai-germany',
      label: 'OpenAI Germany Gateway',
      displayLabel: 'OpenAI Germany',
      subtitle: 'DE Region (optional)',
      zone: 'de-region',
      dataClass: 'non-pii',
      x: 630,
      y: 116,
      width: 180,
      height: 70,
      optional: true,
      hideServiceMarker: true,
      logoSrc: 'assets/openai-logo.svg',
      showLogoTitle: false,
      logoWidth: 104,
      logoHeight: 22,
      shortDescription: 'Service von SAP fuer OpenAI-LLMs auf deutschen SAP-Cloud-Servern (nur non-PII, policy-gesteuert).',
      longDescription: [
        'Stellt OpenAI-Modelle als SAP-Service mit Hosting in Deutschland bereit.',
        'Ermoeglicht regulierte, datenschutzkonforme KI-Aufrufe fuer sensible Einsatzkontexte.',
        'Wird nur fuer policy-freigegebene non-PII Aufgaben verwendet.',
      ],
      purpose: [
        'Regulierte KI-Aufrufe in Deutschland ermoeglichen.',
        'OpenAI-Funktionen ueber SAP-Cloud-Hosting anbinden.',
        'Datenschutzkonforme und nachvollziehbare Nutzung sicherstellen.',
      ],
      inputs: ['Policy-geprüfte non-PII Requests aus der Policy Engine'],
      outputs: ['Antworten aus OpenAI-LLMs ueber SAP Cloud (DE)'],
      securityNotes: [
        'Nur non-PII; PII bleibt lokal/on-prem.',
        'Policy Engine erzwingt Regeln und Logging fuer jeden Aufruf.',
        'Regionale Verarbeitung in Deutschland (SAP Cloud).',
        'Geeignet fuer regulierte Nutzung (z. B. bereits im AOK-Umfeld eingesetzt).',
      ],
      apMapping: 'AP 2.07 / 2.09 – Plattformintegration und Governance',
    },
    {
      id: 'model-providers',
      label: 'Externe Modellanbieter',
      subtitle: 'optional',
      zone: 'us-global',
      dataClass: 'non-pii',
      x: 1280,
      y: 336,
      width: 268,
      height: 120,
      optional: true,
      externalCard: true,
      logoBadges: ['OpenAI', 'Anthropic', 'Mistral'],
      shortDescription: 'Optionale externe Inferenzanbieter für Modellaufrufe ohne PII.',
      longDescription: [
        'Empfängt nur policy-freigegebene non-PII-Anfragen.',
        'Wird zentral über die Policy Engine adressiert.',
        'Kann je nach Betriebsmodus vollständig abgeschaltet werden.',
      ],
      purpose: [
        'Zusätzliche Modellkapazität bereitstellen.',
        'Spezialmodelle optional einbinden.',
        'Skalierung außerhalb On-Prem ermöglichen.',
      ],
      inputs: ['Model Inference Request (non-PII)'],
      outputs: ['Inferenz-Ergebnisse an Policy Engine'],
      securityNotes: ['Keine PII-Weitergabe.', 'Nur via Policy Engine erreichbar.'],
    },
    {
      id: 'external-services',
      label: 'Externe Services',
      subtitle: 'non-PII only (optional)',
      zone: 'us-global',
      dataClass: 'non-pii',
      x: 1280,
      y: 748,
      width: 268,
      height: 130,
      optional: true,
      externalCard: true,
      logoBadges: ['OpenAI', 'Anthropic', 'ElevenLabs', 'Mistral'],
      shortDescription: 'Optionale Drittservices für Funktionen außerhalb des lokalen Kerns.',
      longDescription: [
        'Nimmt nur non-PII-Daten an.',
        'Erweitert CampusConnect um optionale Spezialfunktionen (z. B. Bild-/Videoideen, Live-Transkription, Textpolish).',
        'Bleibt austauschbar durch klare API-Grenzen.',
      ],
      purpose: [
        'Funktionalität optional erweitern.',
        'Spezial-APIs anbinden.',
        'Modulare Integrationen ermöglichen.',
      ],
      inputs: ['External API Requests (non-PII)'],
      outputs: ['Serviceantworten an Policy Engine'],
      securityNotes: ['Nur non-PII erlaubt.', 'Zugriff ausschließlich policy-gesteuert.'],
    },
  ],
  edges: [
    {
      id: 'edge-learner-activity',
      source: 'moodle-lms',
      target: 'lrs',
      label: 'Learner-Aktivitaet (Course UI)',
      dataClass: 'pii',
      style: 'solid',
      optional: false,
      why: 'Lerninteraktionen aus der in Moodle eingebetteten Course UI enthalten personenbezogene Signale und werden daher lokal im LRS gespeichert.',
      policyHint: 'PII verbleibt im On-Prem-Ring; kein externer Exportpfad.',
    },
    {
      id: 'edge-content-publishing',
      source: 'authoring-studio',
      target: 'content-core',
      label: 'Content Publishing',
      dataClass: 'non-pii',
      style: 'solid',
      optional: false,
      why: 'Erstellte Kursinhalte werden zentral in die SSOT übernommen.',
      policyHint: 'Non-PII-Content darf intern weiterverarbeitet werden.',
    },
    {
      id: 'edge-publish-to-moodle',
      source: 'content-core',
      target: 'moodle-lms',
      label: 'Kurs-Publishing zu Moodle',
      dataClass: 'non-pii',
      style: 'solid',
      optional: false,
      why: 'Freigegebene Kursinhalte werden aus der SSOT in Moodle ausgerollt.',
      policyHint: 'Publishing erfolgt innerhalb der Plattformintegration ohne externen PII-Transfer.',
    },
    {
      id: 'edge-insights',
      source: 'lrs',
      target: 'insights-engine',
      label: 'Insights',
      dataClass: 'pii',
      style: 'solid',
      optional: false,
      why: 'PII-nahe Aktivitätsdaten werden lokal analysiert, um Lernfortschritt zu bewerten.',
      policyHint: 'Verarbeitung bleibt innerhalb DE/on-prem.',
    },
    {
      id: 'edge-pathways',
      source: 'content-core',
      target: 'pathway-engine',
      label: 'Pathways / Kompetenzen',
      dataClass: 'non-pii',
      style: 'solid',
      optional: false,
      why: 'Kompetenzmodelle liefern den inhaltlichen Rahmen für adaptive Pfade.',
      policyHint: 'Keine PII im Transfer erforderlich.',
    },
    {
      id: 'edge-insights-sync',
      source: 'insights-engine',
      target: 'pathway-engine',
      label: 'Insights Sync',
      dataClass: 'pii',
      style: 'solid',
      optional: false,
      why: 'Personalisierung benötigt aktuelle, lernendenbezogene Insight-Signale.',
      policyHint: 'PII bleibt lokal und wird nur intern geteilt.',
    },
    {
      id: 'edge-tutor-content',
      source: 'content-core',
      target: 'learning-companion',
      label: 'Tutor Content',
      dataClass: 'non-pii',
      style: 'solid',
      optional: false,
      why: 'Der Tutor erhält kuratierte Inhalte als primären Antwortkontext.',
      policyHint: 'Content stammt aus kontrollierter SSOT.',
    },
    {
      id: 'edge-routing',
      source: 'learning-companion',
      target: 'policy-engine',
      label: 'Routing',
      dataClass: 'non-pii',
      style: 'solid',
      optional: false,
      why: 'Companion-Requests werden vor externer Verarbeitung zentral geprüft.',
      policyHint: 'Policy Engine erzwingt Datenklassifizierungsregeln.',
    },
    {
      id: 'edge-pathway-routing',
      source: 'pathway-engine',
      target: 'policy-engine',
      label: 'Pathway Routing',
      dataClass: 'non-pii',
      style: 'solid',
      optional: false,
      why: 'Pathway-bezogene API-Aufrufe werden über dieselbe Governance-Stelle geroutet.',
      policyHint: 'Einheitliches Enforcement + Logging.',
    },
    {
      id: 'edge-sap-gateway-routing',
      source: 'policy-engine',
      target: 'sap-openai-germany',
      label: 'DE KI-Gateway (OpenAI Germany via SAP)',
      dataClass: 'non-pii',
      style: 'dashed',
      optional: true,
      why: 'Optionale regionale Ausleitung zu OpenAI Germany ueber den SAP-Service mit deutschem Hosting.',
      policyHint: 'Nur non-PII, policy-geprüft und vollständig protokolliert.',
    },
    {
      id: 'edge-external-api',
      source: 'policy-engine',
      target: 'external-services',
      label: 'External API',
      dataClass: 'non-pii',
      style: 'dashed',
      optional: true,
      why: 'Optionale externe Services werden nur mit freigegebenen non-PII-Daten angesprochen.',
      policyHint: 'Optional, abschaltbar und vollständig protokolliert.',
    },
    {
      id: 'edge-model-inference',
      source: 'policy-engine',
      target: 'model-providers',
      label: 'Model Inference',
      dataClass: 'non-pii',
      style: 'dashed',
      optional: true,
      why: 'Externe Inferenz ist möglich, wenn Requests policy-konform und non-PII sind.',
      policyHint: 'PII wird blockiert; nur non-PII darf passieren.',
    },
    {
      id: 'edge-localization',
      source: 'content-core',
      target: 'localization-pipeline',
      label: 'Localization',
      dataClass: 'non-pii',
      style: 'dashed',
      optional: true,
      why: 'Lokalisierung kann optional ausgelagert werden, sofern Inhalte non-PII sind.',
      policyHint: 'Optionaler EU-Cloud-Pfad mit klarer Datenklasse.',
    },
    {
      id: 'edge-translation',
      source: 'learning-companion',
      target: 'language-mediation',
      label: 'Translation',
      dataClass: 'non-pii',
      style: 'dashed',
      optional: true,
      why: 'Runtime-Übersetzung ist optional und nur für non-PII-Anteile vorgesehen.',
      policyHint: 'Kennzeichnung als optionaler, policy-geprüfter externer Pfad.',
    },
  ],
  scenarios: [
    {
      id: 'overview',
      label: 'Übersicht',
      description: 'Komplette Zielarchitektur mit allen aktiven Flüssen und Zonen.',
      edgeIds: [],
      nodeIds: [],
    },
    {
      id: 'roadmap-1-sdg',
      label: 'Architektur 1/5 – SDG CAMPUS',
      description: 'Start in der bestehenden SDG CAMPUS Umgebung: Moodle als Basis, LTI fuer Course UI und Author UI.',
      disableDimming: true,
      strictNodeScope: true,
      visibleZoneIds: ['sdg-campus'],
      visibleGroupIds: ['sdg-campus-cluster'],
      visibleEdgeIds: [],
      edgeIds: [],
      nodeIds: ['moodle-lms'],
    },
    {
      id: 'roadmap-2-onprem',
      label: 'Architektur 2/5 – On-Prem Ausbau',
      description: 'Ergaenzung der lokalen On-Prem-Server fuer Core- und KI-Capabilities.',
      disableDimming: true,
      visibleZoneIds: ['sdg-campus', 'on-prem'],
      visibleGroupIds: ['sdg-campus-cluster', 'core-cluster', 'capabilities-cluster'],
      visibleEdgeIds: [
        'edge-learner-activity',
        'edge-content-publishing',
        'edge-publish-to-moodle',
        'edge-insights',
        'edge-pathways',
        'edge-insights-sync',
        'edge-tutor-content',
        'edge-routing',
        'edge-pathway-routing',
      ],
      edgeIds: [],
      nodeIds: [],
    },
    {
      id: 'roadmap-3-de',
      label: 'Architektur 3/5 – DE Region (OpenAI Germany)',
      description: 'Optionaler DE-Gateway fuer spezialisierte KI-Aufrufe ueber OpenAI Germany als SAP-Service.',
      disableDimming: true,
      visibleZoneIds: ['sdg-campus', 'on-prem', 'de-region'],
      visibleGroupIds: ['sdg-campus-cluster', 'core-cluster', 'capabilities-cluster'],
      visibleEdgeIds: [
        'edge-learner-activity',
        'edge-content-publishing',
        'edge-publish-to-moodle',
        'edge-insights',
        'edge-pathways',
        'edge-insights-sync',
        'edge-tutor-content',
        'edge-routing',
        'edge-pathway-routing',
        'edge-sap-gateway-routing',
      ],
      edgeIds: [],
      nodeIds: [],
    },
    {
      id: 'roadmap-4-eu',
      label: 'Architektur 4/5 – EU Cloud Services',
      description: 'Optionale EU-Services fuer Lokalisierung und Sprachmediation.',
      disableDimming: true,
      visibleZoneIds: ['sdg-campus', 'on-prem', 'de-region', 'eu-cloud'],
      visibleGroupIds: ['sdg-campus-cluster', 'core-cluster', 'capabilities-cluster'],
      visibleEdgeIds: [
        'edge-learner-activity',
        'edge-content-publishing',
        'edge-publish-to-moodle',
        'edge-insights',
        'edge-pathways',
        'edge-insights-sync',
        'edge-tutor-content',
        'edge-routing',
        'edge-pathway-routing',
        'edge-sap-gateway-routing',
        'edge-localization',
        'edge-translation',
      ],
      edgeIds: [],
      nodeIds: [],
    },
    {
      id: 'roadmap-5-global',
      label: 'Architektur 5/5 – US/Global Services',
      description: 'Weitere spezialisierte Services in US/Global, weiterhin nur non-PII und policy-gesteuert.',
      disableDimming: true,
      visibleZoneIds: ['sdg-campus', 'on-prem', 'de-region', 'eu-cloud', 'us-global'],
      visibleGroupIds: ['sdg-campus-cluster', 'core-cluster', 'capabilities-cluster'],
      visibleEdgeIds: [
        'edge-learner-activity',
        'edge-content-publishing',
        'edge-publish-to-moodle',
        'edge-insights',
        'edge-pathways',
        'edge-insights-sync',
        'edge-tutor-content',
        'edge-routing',
        'edge-pathway-routing',
        'edge-sap-gateway-routing',
        'edge-localization',
        'edge-translation',
        'edge-model-inference',
        'edge-external-api',
      ],
      edgeIds: [],
      nodeIds: [],
    },
    {
      id: 'authoring',
      label: 'Kurs erstellen (Authoring)',
      description: 'Von AI-gestützter Inhaltserstellung bis zur zentralen Publikation in den Content Core.',
      edgeIds: ['edge-content-publishing', 'edge-publish-to-moodle', 'edge-localization'],
      nodeIds: ['authoring-studio', 'content-core', 'localization-pipeline', 'audit-hitl', 'moodle-lms'],
    },
    {
      id: 'learning-tracking',
      label: 'Kurs nutzen (Learning & Tracking)',
      description: 'Lernaktivitäten werden lokal erfasst und für Insights ausgewertet.',
      edgeIds: ['edge-learner-activity', 'edge-insights'],
      nodeIds: ['moodle-lms', 'lrs', 'insights-engine'],
    },
    {
      id: 'tutor-pathway',
      label: 'Tutor & Lernpfad (Companion/Pathway)',
      description: 'Personalisierung durch Kombination aus Content, Insights und policy-gesteuertem Routing.',
      edgeIds: [
        'edge-insights-sync',
        'edge-pathways',
        'edge-tutor-content',
        'edge-routing',
        'edge-pathway-routing',
        'edge-sap-gateway-routing',
        'edge-model-inference',
        'edge-external-api',
      ],
      nodeIds: ['insights-engine', 'pathway-engine', 'content-core', 'learning-companion', 'policy-engine', 'sap-openai-germany'],
    },
    {
      id: 'translation',
      label: 'Übersetzung (Localization/Runtime)',
      description: 'Optionale Übersetzungswege für Batch-Lokalisierung und Runtime-Mediation (non-PII only).',
      edgeIds: ['edge-localization', 'edge-translation'],
      nodeIds: ['content-core', 'learning-companion', 'localization-pipeline', 'language-mediation'],
    },
    {
      id: 'ap-201',
      label: 'AP 2.01 – KI-Anwendungen analysieren',
      description: 'Analyse aktueller KI-Konzepte (Tutor, Agenten, Vorschlagslogik, Übersetzung) entlang der Zielarchitektur.',
      edgeIds: [
        'edge-tutor-content',
        'edge-routing',
        'edge-pathways',
        'edge-insights-sync',
        'edge-localization',
        'edge-translation',
        'edge-model-inference',
        'edge-external-api',
      ],
      nodeIds: [
        'learning-companion',
        'pathway-engine',
        'insights-engine',
        'content-core',
        'policy-engine',
        'localization-pipeline',
        'language-mediation',
        'model-providers',
        'external-services',
      ],
    },
    {
      id: 'ap-202',
      label: 'AP 2.02 – Bedarfe, Recht, Ethik',
      description: 'Bedarfe, Rahmenbedingungen und Compliance (inkl. AI-Act/Ethik) mit Fokus auf PII-Grenzen und Governance.',
      edgeIds: [
        'edge-learner-activity',
        'edge-insights',
        'edge-routing',
        'edge-pathway-routing',
        'edge-sap-gateway-routing',
        'edge-model-inference',
        'edge-external-api',
      ],
      nodeIds: [
        'moodle-lms',
        'lrs',
        'insights-engine',
        'policy-engine',
        'audit-hitl',
        'learning-companion',
        'pathway-engine',
        'model-providers',
        'external-services',
      ],
    },
    {
      id: 'ap-203',
      label: 'AP 2.03 – KI-Lernpfade & Personalisierung',
      description: 'Umsetzung intelligenter Lernpfade und personalisierter Lernangebote aus Insights + Kompetenzmodellen.',
      edgeIds: [
        'edge-insights',
        'edge-insights-sync',
        'edge-pathways',
        'edge-pathway-routing',
        'edge-tutor-content',
      ],
      nodeIds: ['lrs', 'insights-engine', 'pathway-engine', 'content-core', 'learning-companion', 'moodle-lms', 'policy-engine'],
    },
    {
      id: 'ap-204',
      label: 'AP 2.04 – KI-Bewertung & Feedback',
      description: 'KI-gestützte Bewertung/Feedback als didaktischer Loop zwischen Lernaktivität, Insights und Companion.',
      edgeIds: ['edge-learner-activity', 'edge-insights', 'edge-insights-sync', 'edge-tutor-content', 'edge-routing'],
      nodeIds: ['moodle-lms', 'lrs', 'insights-engine', 'learning-companion', 'content-core', 'policy-engine'],
    },
    {
      id: 'ap-205',
      label: 'AP 2.05 – KI-Tutorielles System',
      description: 'Personalisierte Hilfestellungen über Learning Companion mit policy-kontrollierter Modellnutzung.',
      edgeIds: ['edge-tutor-content', 'edge-routing', 'edge-sap-gateway-routing', 'edge-model-inference', 'edge-external-api', 'edge-translation'],
      nodeIds: ['learning-companion', 'content-core', 'policy-engine', 'sap-openai-germany', 'moodle-lms', 'language-mediation', 'model-providers', 'external-services'],
    },
    {
      id: 'ap-206',
      label: 'AP 2.06 – Mehrsprachige Lernangebote',
      description: 'Mehrsprachigkeit durch Batch-Lokalisierung und Runtime-Sprachmediation (non-PII only).',
      edgeIds: ['edge-localization', 'edge-translation'],
      nodeIds: ['content-core', 'localization-pipeline', 'learning-companion', 'language-mediation', 'policy-engine'],
    },
    {
      id: 'ap-207',
      label: 'AP 2.07 – Integration in Lernplattform',
      description: 'Einbindung der KI-Tools in Moodle/LTI sowie in die operativen Lernprozesse.',
      edgeIds: [
        'edge-content-publishing',
        'edge-publish-to-moodle',
        'edge-learner-activity',
        'edge-tutor-content',
        'edge-routing',
        'edge-sap-gateway-routing',
        'edge-pathway-routing',
      ],
      nodeIds: ['moodle-lms', 'content-core', 'learning-companion', 'pathway-engine', 'policy-engine', 'sap-openai-germany', 'authoring-studio'],
    },
    {
      id: 'ap-208',
      label: 'AP 2.08 – KI in Kurserstellung',
      description: 'Einsatz von KI im Authoring inklusive Freigabeprozess und optionaler Lokalisierung.',
      edgeIds: ['edge-content-publishing', 'edge-publish-to-moodle', 'edge-localization'],
      nodeIds: ['authoring-studio', 'content-core', 'audit-hitl', 'localization-pipeline', 'moodle-lms'],
    },
    {
      id: 'ap-209',
      label: 'AP 2.09 – Rechtskonforme Handreichungen',
      description: 'Leitlinien für rechtskonforme KI-Nutzung anhand von Policy, Audit und Datenfluss-Grenzen.',
      edgeIds: ['edge-routing', 'edge-pathway-routing', 'edge-sap-gateway-routing', 'edge-model-inference', 'edge-external-api', 'edge-insights'],
      nodeIds: ['policy-engine', 'audit-hitl', 'lrs', 'insights-engine', 'learning-companion', 'pathway-engine', 'sap-openai-germany', 'model-providers', 'external-services'],
    },
  ],
  demoFaq: [
    {
      q: 'Wo liegen Lerndaten?',
      a: 'Im LRS in der PII-Zone (DE/on-prem).',
    },
    {
      q: 'Geht PII an externe LLMs?',
      a: 'Nein. Externe Pfade sind auf non-PII beschränkt und durch die Policy Engine erzwungen.',
    },
    {
      q: 'Wie wird Qualität gesichert?',
      a: 'Über Audit/Freigabe/HITL sowie durchgängiges Policy-Logging.',
    },
  ],
  apMappingSummary: [
    {
      ap: '2.07',
      focus: 'Integration in die Lernplattform',
      components: 'Moodle LMS (inkl. AI Interface/LTI, Course UI, Author UI), Integrationsschnittstellen, OpenAI Germany Gateway',
    },
    {
      ap: '2.08',
      focus: 'KI in der Kurserstellung',
      components: 'Authoring Studio, Content & Competency Core, Policy Engine',
    },
    {
      ap: '2.04',
      focus: 'Bewertung / Feedback / Analyse',
      components: 'Learning Insights Engine, LRS (PII Zone), Audit/Logging',
    },
    {
      ap: '2.03',
      focus: 'Lernpfade',
      components: 'Adaptive Pathway Engine, Content Core, Insights',
    },
    {
      ap: '2.05',
      focus: 'KI-Tutor / Assistenz',
      components: 'Learning Companion, Content Core, Policy Engine',
    },
    {
      ap: '2.06',
      focus: 'Mehrsprachigkeit',
      components: 'Localization Pipeline (Batch), Language Mediation (Runtime)',
    },
    {
      ap: '2.01 / 2.02 / 2.09',
      focus: 'Governance / Ethik / Handreichungen',
      components: 'Audit/Freigabe/HITL, Policy/Logging, SKIS, DE KI-Gateway (OpenAI Germany)',
    },
  ],
  securityPrinciples: [
    'PII bleibt lokal im On-Prem Ring.',
    'Externe Aufrufe sind ausschließlich non-PII und optional.',
    'DE-Region-Aufrufe ueber OpenAI Germany sind als eigener optionaler Gateway-Pfad modelliert.',
    'Policy Engine erzwingt Regeln und schreibt Audit-Logs.',
    'Audit/HITL dient als zusätzliche Qualitäts- und Freigabekontrolle.',
  ],
};

export const NODE_DIMENSIONS = {
  width: 220,
  height: 94,
};
